import { API_KEY_ROLE, type RequestContext, type UserRole } from "./request-context.js";

export const AUTH_ACTIONS = [
  "tenant_profile.read",
  "cloud_accounts.read",
  "cloud_accounts.create_update",
  "cloud_accounts.deactivate",
  "users.read_manage",
  "api_keys.read_manage",
  "api_keys.read_rotate",
  "imports.read",
  "imports.write",
  "price_tables.read",
  "price_tables.create_activate",
  "forecast_models.read",
  "forecast_models.write",
  "forecast_runs.read",
  "forecast_runs.run",
  "scenarios.read_write",
  "optimizer_policies.read",
  "optimizer_policies.write",
  "optimizer_runs.read",
  "optimizer_runs.run",
  "recommendations.read",
  "recommendations.request_approval",
  "recommendations.approve_reject",
  "approvals.read",
  "reports.read",
  "backtests.read_run",
  "audit_log.read",
  "notifications.read",
  "notification_preferences.write",
  "tenant_settings.write",
  "ecosystem_adapters.configure",
] as const;

export type AuthAction = (typeof AUTH_ACTIONS)[number];
export type PolicyDecision = "allow_p1" | "allow_future_p2" | "allow_future_p3" | "deny";
type RolePolicy = Readonly<Record<AuthAction, PolicyDecision>>;

const tenantAdminPolicy: RolePolicy = Object.freeze({
  "tenant_profile.read": "allow_p1",
  "cloud_accounts.read": "allow_p1",
  "cloud_accounts.create_update": "allow_p1",
  "cloud_accounts.deactivate": "allow_p1",
  "users.read_manage": "allow_p1",
  "api_keys.read_manage": "allow_p1",
  "api_keys.read_rotate": "allow_p1",
  "imports.read": "allow_p1",
  "imports.write": "allow_p1",
  "price_tables.read": "allow_p1",
  "price_tables.create_activate": "allow_p1",
  "forecast_models.read": "allow_p1",
  "forecast_models.write": "allow_p1",
  "forecast_runs.read": "allow_p1",
  "forecast_runs.run": "allow_p1",
  "scenarios.read_write": "allow_future_p2",
  "optimizer_policies.read": "allow_p1",
  "optimizer_policies.write": "allow_p1",
  "optimizer_runs.read": "allow_p1",
  "optimizer_runs.run": "allow_p1",
  "recommendations.read": "allow_p1",
  "recommendations.request_approval": "allow_future_p2",
  "recommendations.approve_reject": "allow_future_p2",
  "approvals.read": "allow_future_p2",
  "reports.read": "allow_p1",
  "backtests.read_run": "allow_future_p2",
  "audit_log.read": "allow_future_p2",
  "notifications.read": "allow_future_p2",
  "notification_preferences.write": "allow_future_p2",
  "tenant_settings.write": "allow_p1",
  "ecosystem_adapters.configure": "allow_future_p2",
});

const finopsAnalystPolicy: RolePolicy = Object.freeze({
  "tenant_profile.read": "allow_p1",
  "cloud_accounts.read": "allow_p1",
  "cloud_accounts.create_update": "allow_p1",
  "cloud_accounts.deactivate": "deny",
  "users.read_manage": "deny",
  "api_keys.read_manage": "deny",
  "api_keys.read_rotate": "deny",
  "imports.read": "allow_p1",
  "imports.write": "allow_p1",
  "price_tables.read": "allow_p1",
  "price_tables.create_activate": "deny",
  "forecast_models.read": "allow_p1",
  "forecast_models.write": "allow_p1",
  "forecast_runs.read": "allow_p1",
  "forecast_runs.run": "allow_p1",
  "scenarios.read_write": "allow_future_p2",
  "optimizer_policies.read": "allow_p1",
  "optimizer_policies.write": "deny",
  "optimizer_runs.read": "allow_p1",
  "optimizer_runs.run": "allow_p1",
  "recommendations.read": "allow_p1",
  "recommendations.request_approval": "allow_future_p2",
  "recommendations.approve_reject": "deny",
  "approvals.read": "deny",
  "reports.read": "allow_p1",
  "backtests.read_run": "allow_future_p2",
  "audit_log.read": "deny",
  "notifications.read": "allow_future_p2",
  "notification_preferences.write": "allow_future_p2",
  "tenant_settings.write": "deny",
  "ecosystem_adapters.configure": "deny",
});

const financeApproverPolicy: RolePolicy = Object.freeze({
  "tenant_profile.read": "allow_future_p2",
  "cloud_accounts.read": "allow_future_p2",
  "cloud_accounts.create_update": "deny",
  "cloud_accounts.deactivate": "deny",
  "users.read_manage": "deny",
  "api_keys.read_manage": "deny",
  "api_keys.read_rotate": "deny",
  "imports.read": "allow_future_p2",
  "imports.write": "deny",
  "price_tables.read": "allow_future_p2",
  "price_tables.create_activate": "deny",
  "forecast_models.read": "allow_future_p2",
  "forecast_models.write": "deny",
  "forecast_runs.read": "allow_future_p2",
  "forecast_runs.run": "deny",
  "scenarios.read_write": "allow_future_p2",
  "optimizer_policies.read": "allow_future_p2",
  "optimizer_policies.write": "deny",
  "optimizer_runs.read": "allow_future_p2",
  "optimizer_runs.run": "deny",
  "recommendations.read": "allow_future_p2",
  "recommendations.request_approval": "deny",
  "recommendations.approve_reject": "allow_future_p2",
  "approvals.read": "allow_future_p2",
  "reports.read": "allow_future_p2",
  "backtests.read_run": "allow_future_p2",
  "audit_log.read": "deny",
  "notifications.read": "allow_future_p2",
  "notification_preferences.write": "allow_future_p2",
  "tenant_settings.write": "deny",
  "ecosystem_adapters.configure": "deny",
});

const readOnlyAuditorPolicy: RolePolicy = Object.freeze({
  "tenant_profile.read": "allow_future_p2",
  "cloud_accounts.read": "allow_future_p2",
  "cloud_accounts.create_update": "deny",
  "cloud_accounts.deactivate": "deny",
  "users.read_manage": "deny",
  "api_keys.read_manage": "deny",
  "api_keys.read_rotate": "deny",
  "imports.read": "allow_future_p2",
  "imports.write": "deny",
  "price_tables.read": "allow_future_p2",
  "price_tables.create_activate": "deny",
  "forecast_models.read": "allow_future_p2",
  "forecast_models.write": "deny",
  "forecast_runs.read": "allow_future_p2",
  "forecast_runs.run": "deny",
  "scenarios.read_write": "allow_future_p2",
  "optimizer_policies.read": "allow_future_p2",
  "optimizer_policies.write": "deny",
  "optimizer_runs.read": "allow_future_p2",
  "optimizer_runs.run": "deny",
  "recommendations.read": "allow_future_p2",
  "recommendations.request_approval": "deny",
  "recommendations.approve_reject": "deny",
  "approvals.read": "deny",
  "reports.read": "allow_future_p2",
  "backtests.read_run": "allow_future_p2",
  "audit_log.read": "allow_future_p2",
  "notifications.read": "allow_future_p2",
  "notification_preferences.write": "deny",
  "tenant_settings.write": "deny",
  "ecosystem_adapters.configure": "deny",
});

export const ROLE_ACTION_POLICY: Readonly<Record<UserRole, RolePolicy>> = Object.freeze({
  tenant_admin: tenantAdminPolicy,
  finops_analyst: finopsAnalystPolicy,
  finance_approver: financeApproverPolicy,
  read_only_auditor: readOnlyAuditorPolicy,
});

export const API_KEY_ACTION_POLICY: RolePolicy = Object.freeze({
  "tenant_profile.read": "allow_p1",
  "cloud_accounts.read": "allow_p1",
  "cloud_accounts.create_update": "allow_p1",
  "cloud_accounts.deactivate": "deny",
  "users.read_manage": "deny",
  "api_keys.read_manage": "deny",
  "api_keys.read_rotate": "deny",
  "imports.read": "allow_p1",
  "imports.write": "allow_p1",
  "price_tables.read": "allow_p1",
  "price_tables.create_activate": "deny",
  "forecast_models.read": "allow_p1",
  "forecast_models.write": "allow_p1",
  "forecast_runs.read": "allow_p1",
  "forecast_runs.run": "allow_p1",
  "scenarios.read_write": "deny",
  "optimizer_policies.read": "deny",
  "optimizer_policies.write": "deny",
  "optimizer_runs.read": "allow_p1",
  "optimizer_runs.run": "allow_p1",
  "recommendations.read": "allow_p1",
  "recommendations.request_approval": "allow_future_p2",
  "recommendations.approve_reject": "deny",
  "approvals.read": "deny",
  "reports.read": "allow_p1",
  "backtests.read_run": "allow_future_p2",
  "audit_log.read": "deny",
  "notifications.read": "deny",
  "notification_preferences.write": "deny",
  "tenant_settings.write": "deny",
  "ecosystem_adapters.configure": "deny",
});

const actionSet: ReadonlySet<string> = new Set(AUTH_ACTIONS);

export function isAuthAction(value: unknown): value is AuthAction {
  return typeof value === "string" && actionSet.has(value);
}

export function canPerformAuthAction(
  role: UserRole,
  action: unknown,
  actorType: RequestContext["actorType"] = "user",
): boolean {
  if (!isAuthAction(action)) return false;
  if (actorType === "api_key") {
    return role === API_KEY_ROLE && API_KEY_ACTION_POLICY[action] === "allow_p1";
  }
  return ROLE_ACTION_POLICY[role][action] === "allow_p1";
}
